top30 = [
    "Frankenstein; Or, The Modern Prometheus by Mary Wollstonecraft Shelley (95474)",
    "Pride and Prejudice by Jane Austen (73639)",
    "Moby Dick; Or, The Whale by Herman Melville (64713)",
    "Romeo and Juliet by William Shakespeare (61672)",
    "Middlemarch by George Eliot (47133)",
    "A Room with a View by E. M. Forster (44886)",
    "The Complete Works of William Shakespeare by William Shakespeare (44771)",
    "Little Women; Or, Meg, Jo, Beth, and Amy by Louisa May Alcott (43575)",
    "The Blue Castle: a novel by L. M. Montgomery (39938)",
    "The Enchanted April by Elizabeth Von Arnim (39783)",
    "The Adventures of Ferdinand Count Fathom — Complete by T. Smollett (36952)",
    "Cranford by Elizabeth Cleghorn Gaskell (36619)",
    "The Expedition of Humphry Clinker by T. Smollett (35882)",
    "The Adventures of Roderick Random by T. Smollett (35737)",
    "History of Tom Jones, a Foundling by Henry Fielding (35182)",
    "Twenty years after by Alexandre Dumas and Auguste Maquet (34692)",
    "My Life — Volume 1 by Richard Wagner (34447)",
    "Alice's Adventures in Wonderland by Lewis Carroll (33603)",
    "The Great Gatsby by F. Scott Fitzgerald (33239)",
    "The Picture of Dorian Gray by Oscar Wilde (29359)",
    "A Doll's House : a play by Henrik Ibsen (28986)",
    "The Importance of Being Earnest: A Trivial Comedy for Serious People by Oscar Wilde (26182)",
    "The Yellow Wallpaper by Charlotte Perkins Gilman (25654)",
    "Metamorphosis by Franz Kafka (24249)",
    "A Tale of Two Cities by Charles Dickens (23708)",
    "Crime and Punishment by Fyodor Dostoyevsky (23064)",
    "A Modest Proposal by Jonathan Swift (22062)",
    "Dracula by Bram Stoker (21939)",
    "The Homing Pigeon by United States. Army. Signal Corps and United States. War Department (20967)",
    "The Scarlet Letter by Nathaniel Hawthorne (19047)",
    "Great Expectations by Charles Dickens (18899)",
    "The Strange Case of Dr. Jekyll and Mr. Hyde by Robert Louis Stevenson (18506)",
    "Adventures of Huckleberry Finn by Mark Twain (17600)",
    "Jane Eyre: An Autobiography by Charlotte Brontë (17500)",
    "The Souls of Black Folk by W. E. B. Du Bois (16705)",
    "The Adventures of Sherlock Holmes by Arthur Conan Doyle (15865)",
    "Heart of Darkness by Joseph Conrad (15682)",
    "The Brothers Karamazov by Fyodor Dostoyevsky (15624)",
    "The Iliad by Homer (14319)",
    "Grimms' Fairy Tales by Jacob Grimm and Wilhelm Grimm (13920)",
    "The Prince by Niccolò Machiavelli (13764)",
    "War and Peace by graf Leo Tolstoy (13627)",
    "Don Quijote by Miguel de Cervantes Saavedra (13256)",
    "The Odyssey by Homer (13173)",
    "Ulysses by James Joyce (13124)",
    "A Christmas Carol in Prose; Being a Ghost Story of Christmas by Charles Dickens (12062)",
    "Thus Spake Zarathustra: A Book for All and None by Friedrich Wilhelm Nietzsche (12014)",
    "Wuthering Heights by Emily Brontë (11788)",
    "Walden, and On The Duty Of Civil Disobedience by Henry David Thoreau (11713)",
    "Tractatus Logico-Philosophicus by Ludwig Wittgenstein (11568)",
    "Leviathan by Thomas Hobbes (11423)",
    "The Adventures of Tom Sawyer, Complete by Mark Twain (11315)",
    "The Republic by Plato (10892)",
    "Second Treatise of Government by John Locke (10863)",
    "The Count of Monte Cristo by Alexandre Dumas and Auguste Maquet (10799)",
    "Dubliners by James Joyce (10592)",
    "The Prophet by Kahlil Gibran (10283)",
    "Anne of Green Gables by L. M. Montgomery (9879)",
    "The Romance of Lust: A classic Victorian erotic novel by Anonymous (9866)",
    "Don Quixote by Miguel de Cervantes Saavedra (9793)",
    "Frankenstein; Or, The Modern Prometheus by Mary Wollstonecraft Shelley (9772)",
    "Little Women by Louisa May Alcott (9748)",
    "The Wonderful Wizard of Oz by L. Frank Baum (9403)",
    "Beyond Good and Evil by Friedrich Wilhelm Nietzsche (9337)",
    "Peter Pan by J. M. Barrie (9276)",
    "Winnie-the-Pooh by A. A. Milne (9126)",
    "Meditations by Emperor of Rome Marcus Aurelius (9089)",
    "The divine comedy by Dante Alighieri (8976)",
    "Narrative of the Life of Frederick Douglass, an American Slave by Frederick Douglass (8909)",
    "The War of the Worlds by H. G. Wells (8854)",
    "A Study in Scarlet by Arthur Conan Doyle (8791)",
    "The Kama Sutra of Vatsyayana by Vatsyayana (8731)",
    "Emma by Jane Austen (8662)",
    "White Nights and Other Stories by Fyodor Dostoyevsky (8612)",
    "Calculus Made Easy by Silvanus P. Thompson (8576)",
    "Gulliver's Travels into Several Remote Nations of the World by Jonathan Swift (8508)",
    "Notes from the Underground by Fyodor Dostoyevsky (8479)",
    "Treasure Island by Robert Louis Stevenson (8475)",
    "The Hound of the Baskervilles by Arthur Conan Doyle (8430)",
    "The King in Yellow by Robert W. Chambers (8360)",
    "Sense and Sensibility by Jane Austen (8214)",
    "Beowulf: An Anglo-Saxon Epic Poem (8154)",
    "Carmilla by Joseph Sheridan Le Fanu (8048)",
    "Doctrina Christiana (8019)",
    "The Interesting Narrative of the Life of Olaudah Equiano, Or Gustavus Vassa, The African by Equiano (7874)",
    "Pygmalion by Bernard Shaw (7754)",
    "The King James Version of the Bible (7735)",
    "Frankenstein; Or, The Modern Prometheus by Mary Wollstonecraft Shelley (7725)",
    "Noli Me Tangere by José Rizal (7506)",
    "The Problems of Philosophy by Bertrand Russell (7303)",
    "The Confessions of St. Augustine by Bishop of Hippo Saint Augustine (7221)",
    "The Time Machine by H. G. Wells (7155)",
    "Oliver Twist by Charles Dickens (7097)",
    "The Legend of Sleepy Hollow by Washington Irving (7037)",
    "Anna Karenina by graf Leo Tolstoy (6825)",
    "The Life and Adventures of Robinson Crusoe by Daniel Defoe (6716)",
    "The Reign of Greed by José Rizal (6712)",
    "Incidents in the Life of a Slave Girl, Written by Herself by Harriet A. Jacobs (6693)",
    "The First Book of Adam and Eve by Rutherford Hayes Platt (6607)",
    "On the Duty of Civil Disobedience by Henry David Thoreau (6552)",
]